version: "3"

services:
  view:
    build: ./view
    command: python -m streamlit run launch.py --server.port 80
    volumes:
      - type: volume
        source: shared_volume
        target: /shared_volume

  worker:
    build: ./worker
    command: gunicorn -w 3 api:app --bind 0.0.0.0:9999 --timeout=100
    volumes:
      - type: volume
        source: shared_volume
        target: /shared_volume
    ports:
      - "127.0.0.1:5100:9999"


volumes:
  shared_volume: