version: "3"

services:
  view:
    build: ./view
    command: python -m streamlit run launch.py --server.port 80
    volumes:
      - type: volume
        source: shared_volume
        target: /shared_volume
    ports:
      - "127.0.0.1:5100:80"

  worker:
    build: ./worker
    command: gunicorn -w 3 api:app --bind 0.0.0.0:9999 --timeout=100
    volumes:
      - type: volume
        source: shared_volume
        target: /shared_volume
    restart: always

  nginx:
    build:
      context: ./load_balancer
      dockerfile: Dockerfile
    depends_on:
      - view
      - worker
    restart: always


volumes:
  shared_volume: